### ISSUE TITLE
Figure out issue with zero byte reads in muxer

### ISSUE THREAD

**Issue by agaffney** [cloudstruct/go-ouroboros-network#24]
I'll occasionally run into an error accessing index `0` in an array when the remote host closes the connection unexpectedly (usually in response to a "bad" message sent to them). There should be some additional error checking around this to detect the zero byte read (that we still try to decode as CBOR) to give a more useful error.

**Comment by agaffney** [comment]
```
panic: runtime error: index out of range [0] with length 0

goroutine 24 [running]:
github.com/cloudstruct/go-ouroboros-network/protocol.(*Protocol).recvLoop(0xc0000e4090)
        /home/agaffney/dev/cloudstruct/go-ouroboros-network/protocol/protocol.go:101 +0x545
created by github.com/cloudstruct/go-ouroboros-network/protocol.New
        /home/agaffney/dev/cloudstruct/go-ouroboros-network/protocol/protocol.go:46 +0x17b
```
